### ISSUE TITLE
Task posts on Forum could (should) link back to task on platform

### ISSUE THREAD

**Issue by markwhiting** [crowdresearch/daemo#905]
It would be helpful if there was a link in a post like the following that linked directly back to the platform so that workers could quickly get to it.

<img width="775" alt="screen shot 2017-07-17 at 8 15 21 pm" src="https://user-images.githubusercontent.com/673171/28295166-e1511c3a-6b2c-11e7-9cea-b5d242e17128.png">

**Comment by dmorina** [comment]
Not sure about that, considering that any worker can see this post but not all of them will be able to do it due to boomerang scores or other reasons

**Comment by markwhiting** [comment]
Hum. True. 

The link wouldn't even work for those workers, right?

**Comment by dmorina** [comment]
no, but we would have to design something to explain why they cant see it which changes our initial approach "hide a project until it becomes available to you" 
and after that it would become something like "oh this isn't available to you because you suck :D, but come back later maybe if no one else does it" 
and im not sure that we wanna do that @mbernst  can help maybe

**Comment by markwhiting** [comment]
Sure. That seems reasonable. 

I think its fine not to have a link, just thought it might help some people, but I think this problem is tricky to resolve, so perhaps no need for now.

**Comment by mbernst** [comment]
I think people will figure it out — in particular from other workers, or because the thread is created on the forum.

The nice thing about incentive compatibility is that it doesn't change your behaviors even if you know the system.

So I think the right solution here is to have a page explaining why they don't have access when they try to open it.

**Comment by dmorina** [comment]
so we are fine with exposing information like ratings that the requester has given this worker?

**Comment by mbernst** [comment]
It could be platform etc, so there is plausible deniability.

**Comment by mbernst** [comment]
All that would be clear is that you're not their #1 top rated worker ever

**Comment by shirishgoyal** [comment]
@dmorina what link should users be pointed to?

**Comment by dmorina** [comment]
send them to /task-feed/:projectId 
i will point them right back at you :D

**Comment by shirishgoyal** [comment]
let's make it an infinite loop :joy:

**Comment by shirishgoyal** [comment]
Title in the post now links to the task preview on the platform
