### ISSUE TITLE
Requester status tooltips

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/daemo#968]
<img width="115" alt="screen shot 2017-09-06 at 7 55 18 pm" src="https://user-images.githubusercontent.com/249285/30171369-ca4d9ade-93bf-11e7-89c9-3e37663979e6.png">
Since the discussion thread may already exist, let’s change this to “Discussion”. Also, any easy way to put a badge on that with the number of posts in the thread?

<img width="95" alt="screen shot 2017-09-06 at 7 56 12 pm" src="https://user-images.githubusercontent.com/249285/30171378-d07d1312-93bf-11e7-9697-90c04a0de19a.png">
How about just “copy"

**Comment by dmorina** [comment]
1. it may exist and if it exists it will display a different tooltip "Join Discussion" which seems fine 
no possible to have forum data on the platform (that's why they are separate) and we won't do any integration platform fetching data from forum, these two have to stay decoupled 

2.  copy suggests that the action is read only (always) so that doesn't sound too good for the use case here, maybe another suggestion that's better than "create as copy" or "create copy"

**Comment by dmorina** [comment]
@mbernst see comments above

**Comment by markwhiting** [comment]
+1 for "create copy" or "duplicate" or "duplicate project" which I feel are more intuitive than a "copy and paste" based task description (and is also how Apple prefers to do it)

**Comment by dmorina** [comment]
changed it to Duplicate, rest is kept the same
